# playbook.yml
---
- hosts: servers
  become: yes
  tasks:
    - name: deploy application container
      docker_container:
        image: ampatil/devops-integration:latest
        name: myapplication
        state: started
        auto_remove: true
        ports:
          - "9090:8081"
